import { useEffect, useState } from 'react';
import { Alert, Button, CircularProgress, MenuItem, TextField } from '@mui/material';
import { Link } from 'react-router-dom';
import { api,errorText } from '../../../campus/api';
import { categories,conditions } from '../../../campus/types';
import type { Listing } from '../../../campus/types';
import ProductCard from './ProductCard/ProductCard';
export default function Products(){
 const [items,setItems]=useState<Listing[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [filters,setFilters]=useState({q:'',category:'',condition:'',campus:'',apartment:'',min:'',max:''});const [page,setPage]=useState(0);
 useEffect(()=>{let active=true;setLoading(true); const timer=setTimeout(()=>{const params=Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''));if(params.min)params.min=String(Math.round(Number(params.min)*100));if(params.max)params.max=String(Math.round(Number(params.max)*100));api.get<Listing[]>('/listings',{params:{...params,page}}).then(r=>{if(active){setItems(r.data);setError('');}}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setLoading(false);});},250);return()=>{active=false;clearTimeout(timer);};},[filters,page]);
 const change=(key:string,value:string)=>{setPage(0);setFilters(f=>({...f,[key]:value}));};
 return <><section className="hero"><div><div className="eyebrow">YOUR CAMPUS. YOUR NEIGHBORHOOD.</div><h1>Good finds.<br/><em>Closer to home.</em></h1><p>Secondhand desks, next-semester textbooks, and everything in between. Discover items across apartments and arrange a local pickup.</p><Button component={Link} to="/sell" variant="contained" size="large">Give your things a second life ↗</Button></div><div className="hero-note"><span>THE LOCAL LOOP</span><div className="hero-drawing">↗</div><h2>Less scrolling.<br/>More finding.</h2><p>Browse together.<br/>Reserve one item. Meet locally.</p></div></section>
 <section className="market-heading"><div><div className="eyebrow">A LITTLE CLOSER, A LITTLE GREENER</div><h2>Find your next everyday favorite</h2></div><span>All apartments welcome</span></section>
 <div className="market-layout"><aside className="filters"><h3>Make it your kind of find</h3><TextField label="Search listings" value={filters.q} onChange={e=>change('q',e.target.value)}/>{[['category','Category',categories],['condition','Condition',conditions]].map(([key,name,values])=><TextField select key={key as string} label={name as string} value={filters[key as 'category'|'condition']} onChange={e=>change(key as string,e.target.value)}><MenuItem value="">Any</MenuItem>{(values as string[]).map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField>)}<TextField label="Campus (exact name)" placeholder="North Campus" value={filters.campus} onChange={e=>change('campus',e.target.value)}/><TextField label="Apartment (exact name)" placeholder="Maple Court" value={filters.apartment} onChange={e=>change('apartment',e.target.value)}/><div className="price-filters"><TextField type="number" label="Min $" value={filters.min} onChange={e=>change('min',e.target.value)}/><TextField type="number" label="Max $" value={filters.max} onChange={e=>change('max',e.target.value)}/></div><Button onClick={()=>{setFilters({q:'',category:'',condition:'',campus:'',apartment:'',min:'',max:''});setPage(0);}}>Clear filters</Button><p className="muted">Apartment is a filter, not a membership requirement.</p></aside><section aria-live="polite">{error&&<Alert severity="error">{error}</Alert>}{loading?<CircularProgress aria-label="Loading listings"/>:items.length?<div className="product-grid">{items.map(item=><ProductCard key={item.id} item={item}/>)}</div>:<div className="empty"><h3>No finds just yet</h3><p>Try a different filter, or be the first to list something.</p></div>}<div className="pagination"><Button disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Previous</Button><span>Page {page+1}</span><Button disabled={items.length<24||loading} onClick={()=>setPage(p=>p+1)}>Next</Button></div></section></div></>;
}
